### ISSUE TITLE
Where can I find stops.txt on mta.info?

### ISSUE THREAD

**Issue by zackshapiro** [jonthornton/MtaSanitizer#3]
Hey Jon,

I'm hoping to use this for an MTA-related SMS project I'm working on. I've got the server up and running but I'm unable to find `stops.txt` on mta.info. Any suggestions or links as to where it might be? I'll keep looking.

Thanks!
ZS

**Comment by zackshapiro** [comment]
Nevermind, found them. 

In case anyone comes across this issue in the future, the `stops.txt` files are [here](http://web.mta.info/developers/developer-data-terms.html#data), nested inside of the [New York City Transit Subway download link](http://web.mta.info/developers/data/nyct/subway/google_transit.zip)

**Comment by ebfg** [comment]
Links above are dead. `stops.txt` and `transfers.txt` are now available in this zip: https://rrgtfsfeeds.s3.amazonaws.com/gtfs_subway.zip linked from "Regular GTFS" here: https://www.mta.info/developers
